### PR TITLE
Eslint/prettier configurations

### LINKED ISSUE #20: Implement Prettier Configuration and ESLint Integration for Consistent Code Formatting and Quality Checks.
- Currently, there is no Prettier configuration within the project.
- When the code is formatted, it uses the code editor's default configuration.
- The default configuration may vary from contributor to contributor. This variation leads to a large number of unnecessary changes in the code.
- **To enhance code maintainability and avoid unnecessary changes, consider the following:**
  - Set up a Prettier configuration for consistent code formatting.
  - Integrate a linter, such as ESLint, for code quality checks.

### PR DESCRIPTION
**Pull request by turingAlan**
Resolves #20
@JyothiSwaroopReddy07 have implemented all the ESLint and Prettier configurations which will be necessary to maintain a coding standard in this project right now I have kept some linting rules as warn only while they should be error because there are a lot of those issues.
Also, for once we will need to format all the files with the current prettier configuration which will lead to changes in all the files.

### CODE REVIEW

**Comment by JyothiSwaroopReddy07** [comment]
Can you resolve the merge conflicts.

**Comment by turingAlan** [comment]
@JyothiSwaroopReddy07 done also there was a wrong import PostEditModal.jsx file causing the build to fail which is fixed now.

**Comment by turingAlan** [comment]
We will also need to run `npm run format` which will format each and every JavaScript file according to the local prettier configuration. If we wouldn't do this than in every commit, we will see every unformatted having which has been changed formatted completely.

**Comment by turingAlan** [comment]
@JyothiSwaroopReddy07 shall format all the files in this PR or should I raise another PR for the same?

**Review by JyothiSwaroopReddy07 — APPROVED** [review]

**Comment by JyothiSwaroopReddy07** [comment]
Thanks for the pr. Good Work

**Pull request merged**
