### PR TITLE
Implemented fetching articles from arXiv, pubmed, doi functionality & created resuable code & added countries select dropdown for location in createcommunity page

### PR DESCRIPTION
**Pull request by dinakar17**
1. In the submit article page, I've added two things: i) Improved code reusability by replacing input fields with reusable components `Input.jsx` and `TextareaField.jsx`.  ii) Implemented `ArticleFetcher` component which fetches the articles from the arXiV (ex: arXiv:2106.03744), pubmed (32572182), and doi (10.1007/s00134-020-05985-9)
articlefetcher
2. In the createcommunity page, I've implemented two things
   i) Again improved code reusability by replacing input fields with reusable components `Input.jsx` and `TextareaField.jsx`. 
   ii) Added countries select dropdown using `react-tailwindcss-select` library for selecting the location.

locationselector

### CODE REVIEW

**Comment by JyothiSwaroopReddy07** [comment]
You are not adding the fetched article to the data base. Just fetching is not enough And Also the search bar design can be better.

**Comment by dinakar17** [comment]
articlefetching

Understood. Redesigned the search UI and will try to add the functionalities related to the backend soon.

**Comment by JyothiSwaroopReddy07** [comment]
Looks great design. Can you also add "Add Article" Button to add article to database

**Comment by JyothiSwaroopReddy07** [comment]
Please Also add the Add Article button and using web-scraping techniques to scrap necessary and useful data which are not exposed by API ENDPoints of arxiv, doi. (pubmed I already Have done)

**Comment by dinakar17** [comment]
1. Added a shareable URL link for every comment (review) of the article.

shareable URL link

2. Implemented the logic to fetch arXiv and doi articles and then add them to the database if that article hasn't been added before.
articlefetchaddtodatabase

3. Enhanced Article UI section design by adding tooltips (for clear message) and enhanced style to buttons, text, and other icons
everythingfine
The above is also proof everything's working fine without any breaking changes.
4. Added two unit tests for InputField and Footer using `jest` and `@react-test-library`. Also configured `babel` for parsing `jsx` files while testing.

**Comment by JyothiSwaroopReddy07** [comment]
Sorry for the inconvienence but their are a lot of merge conflicts. Can you resolve them. PR looks great except that

**Pull request closed without merging**
